<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INLT-J1GVBS3" failures="1" tests="10" name="PetStore_User_Test" time="20.515" errors="0" timestamp="2025-08-27T15:50:55 IST">
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="3.453"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.389"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.382"/>
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.426"/>
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.433"/>
  <testcase classname="api.test.DataDrivenTests" name="deleteUsersbyName" time="1.529"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.444"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.54">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUserByName(UserTests.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.954"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.429"/>
</testsuite> <!-- PetStore_User_Test -->
